# Generated by Django 4.1 on 2022-09-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, upload_to='covers', verbose_name='Обложка')),
                ('budget', models.PositiveBigIntegerField(default=0, verbose_name='Бюджет')),
                ('box_office', models.PositiveBigIntegerField(default=0, verbose_name='Сборы')),
                ('runtime', models.PositiveSmallIntegerField(default=0, verbose_name='Продолжительность')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('publicated', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сцена')),
                ('photo', models.ImageField(blank=True, upload_to='scenes', verbose_name='Фото')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_movies.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip-адрес')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Оценка')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_movies.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('occupation', models.CharField(choices=[('A', 'Актер'), ('D', 'Режиссер')], max_length=2, verbose_name='Деятельность')),
                ('birth', models.DateTimeField(blank=True, verbose_name='Дата рождения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='persons', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_movies.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Личность',
                'verbose_name_plural': 'Личности',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='act', to='app_movies.person', verbose_name='Актер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_movies.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='dir', to='app_movies.person', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='app_movies.genre', verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_movies.movie', verbose_name='Фильм')),
                ('to_whom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_movies.comment', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
