# Generated by Django 4.1 on 2022-09-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0002_alter_person_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='publicated',
            new_name='published',
        ),
    ]
