# Generated by Django 4.1 on 2022-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movies', '0003_rename_publicated_movie_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(choices=[('A', 'Актер'), ('D', 'Режиссер'), ('AD', 'Режиссер/Актер')], max_length=2, verbose_name='Деятельность'),
        ),
    ]
